# Generated by Django 4.0.5 on 2022-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='open',
            field=models.FloatField(),
        ),
    ]
