# Generated by Django 4.0.5 on 2022-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0003_bitcoin_ma_200_bitcoin_ma_30_bitcoin_ma_60'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='ma_200',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='ma_30',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='ma_60',
            field=models.FloatField(default=0, null=True),
        ),
    ]
