# Generated by Django 4.0.5 on 2022-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0005_alter_bitcoin_ma_200_alter_bitcoin_ma_30_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='ma_200',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='ma_30',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='ma_60',
            field=models.FloatField(default=0, null=True),
        ),
    ]
